[project]
authors = [{ name = "Michelangelo Setaro", email = "mksetaro@gmail.com" }]
maintainers = [{ name = "Michelangelo Setaro", email = "mksetaro@gmail.com" }]
name = "iot-device-simulator"
version = "1.0.0"
requires-python = ">=3.12"
dependencies = [
    "paho-mqtt>=2.1.0",
    "apscheduler>=3.11.2",
    "orjson>=3.11.5",
    "pydantic>=2.12.5",
]

[project.scripts]
iotsim = "iotsim:main"

[dependency-groups]
dev = ["ruff>=0.14.13"]

[tool.uv.sources]
iotsim = { path = "./iotsim" }
